
-- Create the posts table
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    content TEXT NOT NULL,
    reference TEXT,
    author_name TEXT NOT NULL,
    author_id UUID NOT NULL,
    avatar_url TEXT,
    tag TEXT NOT NULL,
    reactions JSONB NOT NULL DEFAULT '{"amen": 0, "touched": 0, "inspired": 0}'::jsonb
);

-- Enable Row Level Security
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to read posts
CREATE POLICY "Allow public read access" ON public.posts
    FOR SELECT
    USING (true);

-- Policy: Allow authenticated users to create posts
CREATE POLICY "Allow authenticated users to create posts" ON public.posts
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Policy: Allow users to update their own posts
CREATE POLICY "Allow users to update their own posts" ON public.posts
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = author_id)
    WITH CHECK (auth.uid() = author_id);

-- Optional: Add a GIN index on reactions for faster queries
CREATE INDEX IF NOT EXISTS idx_posts_reactions ON public.posts USING GIN (reactions);

-- Optional: Add an index on created_at for faster ordering
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts (created_at DESC);
